---
name: Build and Scan

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

concurrency:
  # yamllint disable-line rule:line-length
  group: gerrit-merge-${{ github.workflow }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

  build-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Node.js project"
        # yamllint disable-line rule:line-length
        uses: lfit/releng-reusable-workflows/.github/actions/node-build-action@5db64208d04fdb0558e8a3a1a1a762b88ffd483e # 2024-09-24

      - name: "Run Sonatype Lifecycle scan"
        # yamllint disable-line rule:line-length
        uses: modeSeven-onap/portal-ng-ui/.github/actions/sonatype-lifecycle-action@master
