---
name: Build and Scan

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  build-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build Node.js project"
        # yamllint disable-line rule:line-length
        uses: lfit/releng-reusable-workflows/.github/actions/node-build-action@5db64208d04fdb0558e8a3a1a1a762b88ffd483e # 2024-09-24

      - name: "Run Sonatype Lifecycle scan"
        # yamllint disable-line rule:line-length
        uses: modeSeven-onap/portal-ng-ui/.github/actions/sonatype-lifecycle-action@master
        with:
          NEXUS_IQ_SERVER: "https://nexus-iq.wl.linuxfoundation.org"
          NEXUS_IQ_USERNAME: "onap-clm"
          NEXUS_IQ_PASSWORD: "${{ secrets.NEXUS_IQ_PASSWORD }}"
          APPLICATION_ID: "onap-portal-ng-ui"
